services:
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

    networks:
      - projectdpr_network

    container_name: projectdpr_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    
    container_name: projectdpr_backend

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - projectdpr_network

    volumes:
      - ./backend:/app
      - /app/node_modules


  frontend:
    build: ./frontend
    container_name: projectdpr_frontend
    
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - projectdpr_network

volumes:
  postgres_data:

networks:
  projectdpr_network:
    driver: bridge